### ISSUE TITLE
Menu not changing when navigating

### ISSUE THREAD

**Issue by avdbrink** [sdey0081/material-dashboard-angular-cli#2]
I would like the menu on the left to show the page I am on, but when I create a link from the main dashboard page to another page and click on it, the active menu item stays Dashboard. Is there a way to change the active menu item from within the new "page" that opens after clicking a link?

**Comment by radiumrasheed** [comment]
can you specify the routes in your description ?

**Comment by ghost** [comment]
Since I've moved to [Fuse Angular Template](https://themeforest.net/item/fuse-angularjs-material-design-admin-template/12931855) and [Fury Angular Template](https://themeforest.net/item/fury-angular-2-material-design-admin-template/19325966), I won't support any technical problem here.
Thanks.
